-- ============================================================================
--  BASELINE CONTENT  ·  the shared question library  ·  run ONCE, after
--  install.sql. 801 rows: the universal library every operator ships with.
--  Ids are explicit and PERMANENT (the per-device seen decks key on them);
--  the identity sequences are advanced past them at the end of this file.
--  Guess the Split ships with fresh, survey-informed phantom seed counts
--  (60-85 total per question, never 50/50): enough weight that the first
--  night's real votes cannot whiplash the split, little enough that a few
--  weeks of real diners genuinely take it over.
-- ============================================================================

-- --- Guess the Split (43 questions) ---
insert into gts_questions (id, option_a, option_b, count_a, count_b) overriding system value values
  (6, 'Sunrise person', 'Sunset person', 33, 52),
  (7, 'Ocean', 'Pool', 40, 30),
  (8, 'Window seat', 'Aisle seat', 50, 31),
  (9, 'Sweet', 'Salty', 33, 33),
  (10, 'Dogs', 'Cats', 46, 31),
  (11, 'Mountains', 'Beach', 29, 33),
  (12, 'Texting', 'Calling', 44, 29),
  (13, 'Summer', 'Fall', 44, 40),
  (14, 'Pancakes', 'Waffles', 39, 30),
  (15, 'Read the book', 'Watch the movie', 33, 47),
  (16, 'Cake', 'Pie', 36, 29),
  (17, 'Crunchy peanut butter', 'Smooth peanut butter', 31, 45),
  (18, 'Board games', 'Video games', 28, 33),
  (19, 'Camping', 'Hotel', 25, 47),
  (20, 'Bacon', 'Sausage', 55, 28),
  (21, 'Iced coffee', 'Hot coffee', 26, 42),
  (22, 'Tacos', 'Pizza', 33, 46),
  (23, 'Concert', 'Comedy show', 38, 26),
  (24, 'Fishing', 'Boating', 33, 42),
  (25, 'Snow day', 'Beach day', 18, 42),
  (26, 'Happy hour', 'Brunch', 38, 33),
  (27, 'Live music', 'Trivia night', 48, 34),
  (28, 'Outdoor seating', 'Bar seats', 39, 28),
  (29, 'Appetizers', 'Dessert', 46, 32),
  (30, 'Coffee', 'Tea', 45, 18),
  (31, 'Burger', 'Hot dog', 55, 19),
  (32, 'Beer', 'Wine', 49, 36),
  (33, 'Chocolate', 'Vanilla', 36, 34),
  (34, 'Thin crust', 'Deep dish', 48, 33),
  (35, 'Mustard', 'Ketchup', 38, 28),
  (36, 'GIF, hard G', 'GIF like "jif"', 53, 24),
  (37, 'Cereal first', 'Milk first', 56, 6),
  (38, 'Aliens are out there', 'We are alone', 48, 25),
  (39, 'Ghosts are real', 'Not real', 33, 51),
  (40, 'Morning shower', 'Night shower', 39, 30),
  (41, 'Early bird', 'Night owl', 45, 35),
  (42, 'Bath', 'Shower', 9, 56),
  (43, 'Booth', 'Table', 53, 23),
  (44, 'Medium rare', 'Well done', 33, 28),
  (45, 'Beach house', 'Mountain cabin', 41, 31),
  (46, 'Pool', 'Hot tub', 46, 37),
  (47, 'Dine in', 'Takeout', 38, 30),
  (48, 'Fold', 'Crumple', 53, 26);

-- --- Who Knows Who (136 questions; {N} = the player's name) ---
insert into wkw_questions (id, prompt, option_a, option_b, option_c, option_d) overriding system value values
  (13, '{N} orders at a restaurant by', 'Getting the same thing every time', 'Asking what the special is', 'Copying whatever everyone else got', 'Changing their mind twice after ordering'),
  (17, '{N} meets a dog and', 'Goes full baby voice immediately', 'Asks the owner a dozen questions', 'Politely pretends to care', 'Avoids it at all costs'),
  (18, 'On a beach day, {N} is', 'First one in the water', 'Under the umbrella all day', 'Taking sixty photos', 'Asleep in twenty minutes'),
  (22, 'At a wedding, {N} is', 'First on the dance floor', 'Holding down the bar', 'Crying during the vows', 'Quietly judging the food'),
  (24, 'If {N} won the lottery, their first move is', 'Telling absolutely no one', 'Quitting their job within the hour', 'One spectacularly dumb purchase', 'Making a spreadsheet'),
  (25, '{N} watches a new show by', 'Bingeing the whole season in a weekend', 'One episode a night, with discipline', 'Falling asleep ten minutes in', 'Reading the plot online first'),
  (27, 'At a concert, {N} is', 'Front row, screaming every lyric', 'Filming the entire thing', 'Hanging back by the bar', 'There for the opening act only'),
  (28, 'Lost in a new city, {N} would', 'Ask a stranger immediately', 'Wander confidently in the wrong direction', 'Follow their phone like a bloodhound', 'Somehow stumble onto the best spot in town'),
  (29, '{N}''s camera roll is mostly', 'Selfies', 'Photos of food', 'Screenshots they''ll never open again', 'Nature shots'),
  (30, 'If {N} had a superpower, it would be', 'Reading minds', 'Never needing sleep', 'Invisibility', 'Talking to animals'),
  (31, '{N} deals with a spider by', 'Calmly relocating it outside', 'Screaming for backup', 'The shoe, no mercy', 'Naming it and letting it stay'),
  (32, '{N}''s fridge is mostly', 'Meal-prepped and labeled', 'Condiments and hope', 'Takeout boxes', 'One very old jar of pickles'),
  (33, 'In a zombie apocalypse, {N} is', 'The fearless leader', 'Hoarding all the snacks', 'First to go, sadly', 'Somehow friends with the zombies'),
  (34, 'If {N} got famous, it would be for', 'An Oscar-winning performance', 'A viral cooking fail', 'Inventing something by accident', 'A very specific world record'),
  (35, 'In a heist movie, {N} is', 'The mastermind', 'The getaway driver', 'The smooth-talking inside man', 'The one who trips the alarm'),
  (36, '{N} in a horror movie is', 'The sensible one who leaves early', 'First to investigate the noise', 'Secretly the villain', 'Survives out of pure spite'),
  (37, 'With a time machine, {N} goes', 'To see the dinosaurs', 'To ancient Rome', 'Straight to the 80s', 'To grab next week''s lottery numbers'),
  (38, 'If {N} joined the circus, they''d be', 'The ringmaster', 'The trapeze star', 'The lion tamer', 'The clown'),
  (40, 'If {N} was a dog, they''d be', 'A golden retriever, all joy', 'A very serious German shepherd', 'A tiny dog with enormous opinions', 'A bulldog napping through it all'),
  (41, '{N} as a ghost would', 'Haunt very politely', 'Rearrange the furniture nightly', 'Follow you to work with commentary', 'Just vibe in the attic'),
  (42, 'If {N} ruled the world, the first law is', 'Mandatory naps', 'Free food everywhere', 'No meetings, ever', 'A national holiday in their honor'),
  (43, 'Aliens land, and {N}', 'Welcomes them with snacks', 'Negotiates on Earth''s behalf', 'Volunteers for abduction', 'Sells the story to the news'),
  (44, 'In a band, {N} is', 'The lead singer', 'The drummer nobody can control', 'The manager with a clipboard', 'Already quit to go solo'),
  (45, '{N} meets their favorite celebrity and', 'Plays it perfectly cool', 'Asks for twelve selfies', 'Forgets their own name', 'Doesn''t recognize them at all'),
  (46, 'The reality show {N} would win is', 'Survivor', 'A baking competition', 'A ballroom dance-off', 'A documentary about napping'),
  (47, 'If {N} was a drink, they''d be', 'A double espresso', 'A frozen margarita', 'Warm chamomile tea', 'Straight hot sauce'),
  (48, '{N}''s hidden talent is probably', 'Freakish trivia memory', 'Dead-on impressions of everyone here', 'Falling asleep anywhere, instantly', 'Finding anything on sale'),
  (49, 'On a deserted island, {N} brings', 'A knife', 'Their own pillow', 'A volleyball to talk to', 'Gallons of sunscreen'),
  (50, '{N}''s past life was probably', 'Royalty, and it shows', 'A pirate', 'The librarian who shushed pirates', 'A very pampered house cat'),
  (51, 'In a fairy tale, {N} is', 'The knight', 'The dragon', 'The mysterious wizard', 'The villager who saw everything'),
  (52, 'If {N} was a kitchen appliance', 'The reliable coffee maker', 'An air fryer, very trendy', 'A blender at full volume', 'The smoke alarm'),
  (53, 'In a talent show, {N}''s act is', 'Magic, with mixed results', 'A dramatic poetry reading', 'Juggling something dangerous', 'A full-choreography lip sync'),
  (54, '{N} wins an award, and the speech is', 'Two words, then gone', 'A tearful thank-you to everyone ever', 'Clearly improvised chaos', 'Written years ago, just in case'),
  (55, 'If {N} opened a restaurant, it would be', 'Fine dining, reservations only', 'A beloved greasy spoon', 'A food truck with a cult following', 'Closed within the month'),
  (56, '{N} finds $20 on the sidewalk and', 'Pockets it, zero hesitation', 'Asks everyone within earshot', 'Gives it away', 'Buys the table a round'),
  (57, 'On a game show, {N} would', 'Win the whole thing, calmly', 'Freeze on the easiest question', 'Argue with the host', 'Become a fan favorite and still lose'),
  (58, 'If {N} was weather, they''d be', 'A perfect sunny day', 'A surprise thunderstorm', 'A heatwave that overstays', 'A light drizzle that never quite stops'),
  (59, 'At a museum, {N} is', 'Reading every single plaque', 'Done in twenty minutes', 'Straight to the gift shop', 'Touching things they shouldn''t'),
  (60, 'In a courtroom drama, {N} is', 'The unflappable judge', 'The dramatic lawyer', 'The surprise witness', 'Guilty'),
  (61, 'If {N} was a mythical creature', 'A wise old dragon', 'A mischievous fairy', 'Bigfoot, rarely photographed', 'A mermaid, dramatic'),
  (63, 'In a pirate crew, {N} is', 'The captain', 'The lookout asleep in the nest', 'The one guarding the treasure', 'The parrot''s best friend'),
  (64, 'If {N} was furniture, they''d be', 'The comfy recliner', 'A wobbly bar stool', 'An antique nobody may touch', 'A futon, adaptable'),
  (65, '{N}''s warning label would read', '"May burst into song"', '"Contents under pressure"', '"Prone to wandering off"', '"Feeds on gossip"'),
  (66, 'If {N} was a car, they''d be', 'A luxury sedan', 'A muddy Jeep', 'A minivan', 'A sports car'),
  (67, 'In a sitcom, {N} is', 'The sarcastic neighbor', 'The lovable mess', 'The scheming best friend', 'The one with the catchphrase'),
  (68, '{N}''s supervillain lair would be', 'A volcano fortress', 'A cozy cabin, location undisclosed', 'A yacht, taxes unclear', 'The back booth of a bar'),
  (69, 'If {N} started a club, it would be', 'A book club that never reads', 'A secret supper club', 'A conspiracy discussion group', 'A very serious pickleball league'),
  (70, 'If {N} was a spice', 'Cinnamon, comforting', 'Cayenne, a little dangerous', 'Salt, essential', 'Saffron, expensive taste'),
  (71, 'If {N} had a podcast, it would be', 'True crime, whispered', 'Their week, unedited', 'Interviews with strangers', 'Cancelled after two episodes'),
  (72, 'In a medieval kingdom, {N} is', 'The monarch', 'The court jester', 'The knight', 'The peasant leading a revolt'),
  (73, '{N}''s entrance music would be', 'Heavy metal', 'Smooth jazz', 'A movie soundtrack', 'The Jeopardy theme'),
  (74, 'If {N} was a house, they''d be', 'A beach bungalow', 'A tidy modern condo', 'A farmhouse with a porch', 'A haunted Victorian'),
  (75, '{N}''s secret government file is labeled', '"Mostly harmless"', '"Do not engage before noon"', '"Charming, monitor closely"', '"Knows too much"'),
  (76, 'In an escape room, {N} is', 'Solving it alone', 'Reading every clue out loud', 'Trying the same door repeatedly', 'Negotiating with the staff'),
  (77, '{N} as a barista would', 'Remember every regular''s order', 'Write names wrong on purpose', 'Give free refills to everyone', 'Unionize by Friday'),
  (78, 'If {N} joined the space program, they''d be', 'The mission commander', 'Ground control', 'The one posting from orbit', 'Left at the launch site'),
  (79, 'The movie of {N}''s life is rated', 'G', 'PG', 'PG-13', 'R'),
  (80, 'In the Wild West, {N} is', 'The sheriff', 'The outlaw', 'The saloon owner who hears everything', 'The tumbleweed'),
  (81, 'If {N} was a phone app', 'The alarm everyone snoozes', 'A meditation app', 'A game you can''t stop playing', 'A personal finance app'),
  (82, 'If {N} was royalty, their title is', 'The Reasonable', 'The Bold', 'The Hungry', 'The Dramatic'),
  (83, '{N}''s doomsday prep consists of', 'A stocked bunker', 'Snacks and a flashlight', 'Charm, they''ll be fine', 'Whatever the group brought'),
  (84, '{N}''s masterclass would teach', 'Getting free upgrades', 'Grill mastery', 'The art of leaving on time', 'Winning any argument'),
  (85, 'As a superhero sidekick, {N} would', 'Outshine the hero', 'Handle the paperwork', 'Get captured constantly', 'Quit and go freelance'),
  (86, 'If {N} was a candle scent', 'Fresh linen', 'Campfire', 'Ocean breeze', 'Bacon'),
  (87, 'If {N} is controlling the music, they play', 'Crowd pleasers only', 'Deep cuts nobody knows', 'The same three songs', 'A podcast, somehow'),
  (88, 'In a cooking competition, {N} gets praised for', 'Presentation', 'Bold flavors', 'Speed', 'Effort'),
  (89, '{N}''s retirement plan is', 'A beach house somewhere', 'Professional grandkid spoiling', 'Never retiring, thriving', 'A suspiciously nice RV'),
  (90, '{N} as a landlord would', 'Fix everything the same day', 'Raise rent apologetically', 'Befriend every tenant', '"Handle it" never'),
  (91, '{N}''s signature potluck dish is', 'A labor of love', 'Store-bought, rebranded', 'The same dish since 2009', 'Napkins'),
  (92, 'During a power outage, {N}', 'Has candles ready', 'Tells ghost stories', 'Panics about the fridge', 'Sleeps through it'),
  (93, 'If {N} wrote a country song, it''s about', 'A truck', 'Heartbreak at the shore', 'Their dog', 'A grudge, very specific'),
  (94, 'If {N} could wake up with one superpower, they would choose', 'Flying', 'Invisibility', 'Reading minds', 'Stopping time'),
  (95, '{N}''s surprising hidden talent is', 'Singing on pitch', 'Doing impressions', 'Parallel parking', 'Wiggling their ears'),
  (96, 'If {N} could instantly master one thing, it would be', 'Playing guitar', 'Speaking five languages', 'Cooking like a chef', 'Dancing on beat'),
  (97, 'On a midnight fridge raid, {N} reaches for', 'Cold pizza', 'Ice cream', 'Cheese and crackers', 'Leftover noodles'),
  (98, '{N}''s signature snack is always', 'Something sweet', 'Something salty', 'Something spicy', 'Something sour'),
  (99, 'At the movie theater, {N} grabs', 'A giant popcorn', 'Sour candy', 'Loaded nachos', 'Smuggled snacks'),
  (102, 'If {N} lost their phone for a day, they would', 'Barely notice', 'Panic instantly', 'Feel weirdly free', 'Borrow one fast'),
  (103, 'If {N} were a weather forecast, they would be', 'Endless sunshine', 'A sudden storm', 'Cozy fog', 'Clear and breezy'),
  (104, 'If {N} were a household pet, they would be', 'A loyal dog', 'An aloof cat', 'A chatty parrot', 'A chill goldfish'),
  (105, 'If {N} were an emoji, they would be', 'The laughing tears', 'The cool shades', 'The upside down face', 'The sparkles'),
  (106, 'If {N} were a drink order, they would be', 'A green smoothie', 'An energy drink', 'A fancy cocktail', 'Just water'),
  (107, 'If {N} were a dessert, they would be', 'Chocolate cake', 'Vanilla ice cream', 'A fruit tart', 'Cotton candy'),
  (108, '{N}''s perfect free Saturday is', 'A long hike', 'A show binge', 'A big brunch', 'An all day nap'),
  (109, 'On the dance floor, {N} is', 'First one out', 'One signature move', 'Hiding by snacks', 'Secretly amazing'),
  (110, 'Behind the wheel, {N} is', 'Ten under the limit', 'A calm cruiser', 'A total lead foot', 'Lost without GPS'),
  (111, '{N}''s everyday carry item is', 'A huge water bottle', 'Wireless earbuds', 'A stuffed tote', 'Just lip balm'),
  (112, '{N}''s ultimate comfort show is', 'A sitcom rerun', 'A true crime doc', 'A cooking show', 'A childhood cartoon'),
  (113, 'If {N} were an animal, they would be', 'A golden retriever', 'A house cat', 'A raccoon', 'An owl'),
  (114, 'The award {N} would win is', 'Class clown', 'Best dressed', 'Most likely to be famous', 'Most dramatic'),
  (115, 'If {N} were a board game, they would be', 'Monopoly', 'Jenga', 'Chess', 'Twister'),
  (116, 'If {N} were a holiday, they would be', 'Halloween', 'New Year''s Eve', 'Thanksgiving', 'Valentine''s Day'),
  (117, 'On a reality TV show, {N} would be', 'The fan favorite', 'The villain', 'The first eliminated', 'The dark horse'),
  (118, 'If {N} opened a business, it would be', 'A cozy cafe', 'A tattoo parlor', 'A bookstore', 'A food truck'),
  (119, 'If {N} were a piece of furniture, they would be', 'A recliner', 'A bar stool', 'A bean bag', 'An antique desk'),
  (120, 'If {N} were a season, they would be', 'Spring', 'Summer', 'Autumn', 'Winter'),
  (121, 'At a theme park, {N} is', 'The roller coaster', 'The lazy river', 'The haunted house', 'The carousel'),
  (122, 'If {N} were a shoe, they would be', 'Running sneakers', 'Cowboy boots', 'Flip flops', 'Dress shoes'),
  (123, 'If {N} were a movie genre, they would be', 'A comedy', 'A horror flick', 'A rom com', 'An action blockbuster'),
  (124, 'At a wedding, {N} is most likely to be', 'Crying during the vows', 'Running the dance floor', 'Sneaking extra cake', 'Best friends with the bartender'),
  (125, 'If {N} planned a group trip, the vibe would be', 'Packed hourly itinerary', 'Zero plans, pure chaos', 'A spreadsheet nobody reads', 'Whatever the group chat decides'),
  (126, 'In the group chat, {N} is the one who', 'Sends the 3am voice memo', 'Leaves everyone on read', 'Replies with only memes', 'Plans the whole event solo'),
  (128, 'At a dinner out, {N} is the one who', 'Orders for the whole table', 'Grabs the check first', 'Takes photos of every plate', 'Still deciding when food arrives'),
  (129, 'When the group needs a designated driver, {N} is', 'Always the volunteer', 'Suddenly unreachable', 'Asleep in the back seat', 'The one nobody trusts'),
  (130, 'When a party winds down, {N} is', 'First to sneak out', 'Last one standing', 'Deep in a heart to heart', 'Helping the host clean up'),
  (131, 'If {N} threw a party, the theme would be', 'Fancy dress required', 'Bring your own everything', 'A surprise for someone', 'No theme, just vibes'),
  (132, 'On a night out, {N} is the friend who', 'Knows every doorman', 'Wants to leave early', 'Starts the conga line', 'Rounds everyone up for food'),
  (133, 'When plans fall through last minute, {N} is the one who', 'Saves the whole night', 'Says told you so', 'Was already in pajamas', 'Books something even better'),
  (134, 'At brunch with friends, {N} is', 'First to arrive', 'An hour late', 'Splitting the bill exactly', 'Ordering the whole menu'),
  (135, 'If the friend group formed a band, {N} would be', 'The dramatic lead singer', 'The chill drummer', 'The manager who books gigs', 'The one who quits early'),
  (136, 'When the group plays board games, {N} is', 'Ruthlessly competitive', 'Making up new rules', 'Flipping the table', 'Just there for snacks'),
  (137, 'At a barbecue, {N} would be', 'Commanding the grill', 'First in the food line', 'Starting a backyard game', 'Napping in a lawn chair'),
  (138, 'If {N} hosted game night, it would end with', 'A heated rules debate', 'Everyone laughing too hard', 'One dramatic walkout', 'A surprise midnight snack run'),
  (139, 'On a group vacation, {N} is in charge of', 'The daily schedule', 'Finding the best food', 'The group photos', 'Absolutely nothing'),
  (140, 'At a birthday party, {N} is the one who', 'Brings the loudest energy', 'Forgot to bring a gift', 'Organized the whole surprise', 'Leaves before cake'),
  (141, 'If the group got lost in a new city, {N} would', 'Confidently lead the wrong way', 'Ask a stranger for help', 'Panic quietly', 'Turn it into an adventure'),
  (142, 'If the friends started a group chat drama, {N} would be', 'The one who started it', 'The peacemaker in the middle', 'Screenshotting for later', 'Blissfully unaware'),
  (143, '{N} finds a wallet full of cash on the sidewalk and', 'Tracks down the owner', 'Turns it in to police', 'Keeps the cash', 'Posts it online'),
  (144, '{N} is stuck in a broken elevator with four strangers and', 'Cracks jokes nonstop', 'Calls for help', 'Quietly panics', 'Takes charge'),
  (145, '{N} wins the lottery jackpot overnight and', 'Quits the next morning', 'Tells absolutely no one', 'Throws a huge party', 'Hides the ticket'),
  (146, 'It is the last day on earth and {N}', 'Calls everyone they love', 'Eats every dessert', 'Throws one last party', 'Sits quietly outside'),
  (147, '{N} spots a huge celebrity at the next table and', 'Marches over immediately', 'Pretends not to notice', 'Sneaks a photo', 'Asks for an autograph'),
  (148, '{N} finds a lost dog with no collar and', 'Adopts it instantly', 'Knocks on every door', 'Posts flyers everywhere', 'Drives to the shelter'),
  (149, 'A genie offers {N} three wishes and {N}', 'Wishes for more wishes', 'Wishes everyone happy', 'Wishes for riches', 'Wishes for superpowers'),
  (150, '{N} wakes up invisible for one day and', 'Robs a bank', 'Spies on friends', 'Sneaks into movies', 'Does absolutely nothing'),
  (151, 'If {N} gets cast in a blockbuster movie they would be', 'The fearless hero', 'The scheming villain', 'The comic sidekick', 'The mysterious stranger'),
  (152, 'A UFO lands right in front of {N} and {N}', 'Walks straight aboard', 'Films the whole thing', 'Runs for the hills', 'Tries to say hello'),
  (153, '{N} is stranded alone on a desert island and', 'Builds a raft', 'Names the coconuts', 'Waits for rescue', 'Explores every inch'),
  (154, 'Handed a time machine with one trip, {N}', 'Zooms to the future', 'Visits the dinosaurs', 'Fixes a past mistake', 'Leaves it untouched'),
  (155, 'The whole city loses power for a week and {N}', 'Hosts the block party', 'Hoards the flashlights', 'Sleeps through it', 'Checks on neighbors'),
  (156, '{N}''s car breaks down in the middle of nowhere and', 'Pops the hood open', 'Flags down a stranger', 'Starts walking', 'Calls everyone at once'),
  (157, '{N} witnesses a stranger shoplifting and', 'Says something loudly', 'Tells an employee', 'Looks the other way', 'Offers to pay'),
  (158, '{N} is made president for one day and', 'Declares a holiday', 'Reads every briefing', 'Naps in the office', 'Renames the country'),
  (159, '{N} finds a treasure map tucked in an old book and', 'Grabs a shovel now', 'Researches it first', 'Sells it fast', 'Frames it on the wall'),
  (160, '{N} bumps right into their celebrity crush and', 'Freezes up', 'Plays it cool', 'Talks way too much', 'Bolts the other way'),
  (161, '{N} wakes up 100 years in the future and', 'Explores like a tourist', 'Searches for family', 'Panics immediately', 'Blends right in');

-- --- Trivia (293 questions) ---
insert into trivia_questions (id, question, correct_answer, wrong_1, wrong_2, wrong_3) overriding system value values
  (1, 'How many bones are in the adult human body?', '206', '198', '224', '187'),
  (3, 'What is the largest ocean on Earth?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'),
  (5, 'What gas do plants absorb from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'),
  (6, 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Pablo Picasso', 'Vincent van Gogh', 'Claude Monet'),
  (8, 'What is the tallest land animal?', 'Giraffe', 'Elephant', 'Horse', 'Camel'),
  (10, 'Which metal is liquid at room temperature?', 'Mercury', 'Iron', 'Lead', 'Tin'),
  (13, 'What is the smallest prime number?', 'Two', 'One', 'Three', 'Zero'),
  (15, 'Which country has the longest coastline in the world?', 'Canada', 'Russia', 'Australia', 'Norway'),
  (16, 'What is the only fruit with its seeds on the outside?', 'Strawberry', 'Raspberry', 'Blackberry', 'Fig'),
  (17, 'Which state was the first to ratify the U.S. Constitution?', 'Delaware', 'Virginia', 'Pennsylvania', 'New Jersey'),
  (18, 'How many hearts does an octopus have?', 'Three', 'One', 'Two', 'Four'),
  (19, 'What spirit goes in a traditional mojito?', 'Rum', 'Tequila', 'Vodka', 'Gin'),
  (20, 'What is the national animal of Scotland?', 'The unicorn', 'The lion', 'The stag', 'The golden eagle'),
  (21, 'In what year did the Titanic sink?', '1912', '1905', '1918', '1923'),
  (22, 'Who has won the most Grammy Awards of all time?', 'Beyoncé', 'Michael Jackson', 'Taylor Swift', 'Stevie Wonder'),
  (23, 'What is the main ingredient in hummus?', 'Chickpeas', 'Lentils', 'White beans', 'Peas'),
  (25, 'How many keys are on a standard piano?', '88', '76', '92', '100'),
  (26, 'Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Mother Teresa', 'Jane Addams', 'Rosalind Franklin'),
  (27, 'A group of crows is called a what?', 'A murder', 'A gaggle', 'A parliament', 'A flock'),
  (28, 'The tea bag was invented in which country?', 'United States', 'China', 'England', 'India'),
  (29, 'What is the smallest country in the world?', 'Vatican City', 'Monaco', 'Malta', 'San Marino'),
  (30, 'How many time zones does Russia span?', 'Eleven', 'Seven', 'Nine', 'Thirteen'),
  (33, 'Which U.S. state borders exactly one other state?', 'Maine', 'Rhode Island', 'Alaska', 'Florida'),
  (34, 'Which country drinks the most coffee per person?', 'Finland', 'Italy', 'United States', 'Brazil'),
  (35, 'What is the currency of Switzerland?', 'The franc', 'The euro', 'The krone', 'The mark'),
  (36, 'Which president is on the $50 bill?', 'Ulysses S. Grant', 'Andrew Jackson', 'Benjamin Franklin', 'Alexander Hamilton'),
  (37, 'What is the longest bone in the human body?', 'The femur', 'The tibia', 'The humerus', 'The collarbone'),
  (38, 'Who painted The Starry Night?', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dali', 'Pablo Picasso'),
  (39, 'In what year did World War II end?', '1945', '1943', '1947', '1950'),
  (40, 'Which country has the most natural lakes?', 'Canada', 'Finland', 'Russia', 'United States'),
  (41, 'Japanese sake is made from what?', 'Rice', 'Plums', 'Barley', 'Potatoes'),
  (42, 'Which chess piece only moves diagonally?', 'The bishop', 'The rook', 'The knight', 'The queen'),
  (43, 'Which fast food chain''s logo is a red-haired girl?', 'Wendy''s', 'Dairy Queen', 'Arby''s', 'Sonic'),
  (44, 'What animal is on the Porsche logo?', 'A horse', 'A bull', 'A lion', 'A ram'),
  (45, 'What surface is Wimbledon played on?', 'Grass', 'Clay', 'Hard court', 'Carpet'),
  (46, 'Which language has the most native speakers?', 'Mandarin Chinese', 'English', 'Spanish', 'Hindi'),
  (47, 'Cavendish is a variety of which fruit?', 'Banana', 'Apple', 'Mango', 'Pear'),
  (48, 'How many squares are on a chessboard?', '64', '81', '100', '72'),
  (49, 'A group of owls is called a what?', 'A parliament', 'A congress', 'A covey', 'A hoot'),
  (50, 'What is the tallest mountain in North America?', 'Denali', 'Mount Whitney', 'Mount Rainier', 'Pikes Peak'),
  (51, 'Coca-Cola was invented by a pharmacist in which city?', 'Atlanta', 'Nashville', 'New Orleans', 'St. Louis'),
  (52, 'What does SPF stand for on sunscreen?', 'Sun Protection Factor', 'Solar Protection Formula', 'Skin Protection Factor', 'Sun Prevention Filter'),
  (53, 'The Snickers bar is named after what?', 'A horse', 'The inventor''s dog', 'The sound of a laugh', 'A small town in Texas'),
  (54, 'Paella comes from which country?', 'Spain', 'Italy', 'Portugal', 'Mexico'),
  (55, 'Machu Picchu is in which country?', 'Peru', 'Mexico', 'Chile', 'Bolivia'),
  (56, 'Which city hosted the first modern Olympics in 1896?', 'Athens', 'Paris', 'Rome', 'London'),
  (57, 'Which organ produces insulin?', 'The pancreas', 'The liver', 'The kidneys', 'The spleen'),
  (58, 'What color is a polar bear''s skin?', 'Black', 'White', 'Pink', 'Grey'),
  (59, 'Which of Snow White''s dwarfs comes first alphabetically?', 'Bashful', 'Doc', 'Dopey', 'Grumpy'),
  (60, 'Who was the Beatles'' drummer?', 'Ringo Starr', 'Paul McCartney', 'John Lennon', 'George Harrison'),
  (61, 'What is the largest desert in the world?', 'Antarctica', 'The Sahara', 'The Gobi', 'The Arabian'),
  (62, 'Which gas makes up most of Earth''s air?', 'Nitrogen', 'Oxygen', 'Carbon dioxide', 'Hydrogen'),
  (63, 'In what year did the Berlin Wall fall?', '1989', '1985', '1991', '1979'),
  (64, 'Which element has the chemical symbol K?', 'Potassium', 'Krypton', 'Calcium', 'Copper'),
  (65, 'Who first flew solo across the Atlantic?', 'Charles Lindbergh', 'Amelia Earhart', 'Howard Hughes', 'Wiley Post'),
  (66, 'Which country was formerly called Siam?', 'Thailand', 'Vietnam', 'Cambodia', 'Myanmar'),
  (67, 'What is the rarest of the eight main blood types?', 'AB negative', 'O negative', 'B negative', 'A negative'),
  (68, 'In Greek mythology, who flew too close to the sun?', 'Icarus', 'Apollo', 'Hermes', 'Achilles'),
  (69, 'What is the longest running Broadway show of all time?', 'The Phantom of the Opera', 'Cats', 'Chicago', 'Les Miserables'),
  (70, 'Which planet takes the longest to orbit the sun?', 'Neptune', 'Uranus', 'Saturn', 'Jupiter'),
  (71, 'Which country has the most islands in the world?', 'Sweden', 'Indonesia', 'The Philippines', 'Japan'),
  (72, 'Which U.S. president served the shortest time in office?', 'William Henry Harrison', 'James Garfield', 'Zachary Taylor', 'Gerald Ford'),
  (73, 'Who wrote The Great Gatsby?', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'William Faulkner'),
  (74, 'What is the currency of South Africa?', 'The rand', 'The shilling', 'The peso', 'The dinar'),
  (75, 'Montezuma ruled which empire?', 'The Aztec', 'The Inca', 'The Maya', 'The Toltec'),
  (76, 'What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakesh', 'Fez'),
  (77, 'Which composer was almost completely deaf when he wrote his Ninth Symphony?', 'Beethoven', 'Mozart', 'Bach', 'Chopin'),
  (78, 'What was the first country to give women the vote?', 'New Zealand', 'United States', 'United Kingdom', 'France'),
  (79, 'Which element is named after the Greek word for the sun?', 'Helium', 'Hydrogen', 'Neon', 'Argon'),
  (80, 'Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello'),
  (81, 'The deepest known point in the ocean is in which trench?', 'The Mariana Trench', 'The Tonga Trench', 'The Java Trench', 'The Puerto Rico Trench'),
  (82, 'Which country drinks the most tea per person?', 'Turkey', 'England', 'China', 'India'),
  (83, 'Which novel begins "Call me Ishmael"?', 'Moby-Dick', 'Treasure Island', 'The Old Man and the Sea', 'Robinson Crusoe'),
  (84, 'The Battle of Hastings was fought in which year?', '1066', '1215', '1415', '966'),
  (85, 'Which country hosted and won the first World Cup in 1930?', 'Uruguay', 'Brazil', 'Italy', 'England'),
  (86, 'What metal is the Statue of Liberty''s skin made of?', 'Copper', 'Bronze', 'Iron', 'Steel'),
  (87, 'Which country has the world''s oldest continuously used national flag?', 'Denmark', 'United Kingdom', 'Japan', 'Switzerland'),
  (88, 'Titan is the largest moon of which planet?', 'Saturn', 'Jupiter', 'Neptune', 'Uranus'),
  (89, 'Who invented the printing press?', 'Johannes Gutenberg', 'Benjamin Franklin', 'Thomas Edison', 'Leonardo da Vinci'),
  (90, 'The Wars of the Roses were fought between which two families?', 'York and Lancaster', 'Tudor and Stuart', 'Windsor and Hanover', 'Montague and Capulet'),
  (91, 'What was the first capital city of the United States?', 'New York City', 'Philadelphia', 'Washington', 'Boston'),
  (92, 'Alexander the Great was king of which ancient kingdom?', 'Macedonia', 'Sparta', 'Athens', 'Persia'),
  (93, 'Which two countries share the longest border?', 'US and Canada', 'US and Mexico', 'Russia and China', 'Argentina and Chile'),
  (94, 'What is the capital of Turkey?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'),
  (95, 'Which African country was never colonized?', 'Ethiopia', 'Kenya', 'Ghana', 'Nigeria'),
  (96, 'The Amazon River empties into which ocean?', 'Atlantic', 'Pacific', 'Indian', 'Southern'),
  (97, 'Which U.S. state has the most coastline?', 'Alaska', 'California', 'Florida', 'Hawaii'),
  (98, 'Venice is built on roughly how many islands?', 'More than 100', 'About 20', 'About 50', 'Exactly 12'),
  (99, 'Which country sits on both Europe and Asia?', 'Turkey', 'Greece', 'Egypt', 'Morocco'),
  (100, 'What is the smallest ocean?', 'Arctic', 'Indian', 'Southern', 'Atlantic'),
  (101, 'Mount Kilimanjaro is in which country?', 'Tanzania', 'Kenya', 'Ethiopia', 'Uganda'),
  (102, 'The Bosphorus strait splits which city?', 'Istanbul', 'Athens', 'Cairo', 'Dubai'),
  (103, 'Who was the first human in space?', 'Yuri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'John Glenn'),
  (104, 'Ancient Rome was built on how many hills?', 'Seven', 'Five', 'Nine', 'Three'),
  (105, 'Who was Britain''s prime minister for most of World War II?', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Anthony Eden'),
  (106, 'The Louisiana Purchase was bought from which country?', 'France', 'Spain', 'Mexico', 'England'),
  (107, 'In which decade did the American Civil War begin?', '1860s', '1850s', '1870s', '1840s'),
  (108, 'How many wives did King Henry VIII have?', 'Six', 'Four', 'Five', 'Eight'),
  (109, 'The Great Fire of London happened in which century?', 'The 1600s', 'The 1500s', 'The 1700s', 'The 1400s'),
  (110, 'Washington''s cherry blossom trees were a gift from which country?', 'Japan', 'China', 'Korea', 'France'),
  (111, 'Who assassinated Abraham Lincoln?', 'John Wilkes Booth', 'Lee Harvey Oswald', 'Aaron Burr', 'Charles Guiteau'),
  (112, 'The Rosetta Stone unlocked which written language?', 'Egyptian hieroglyphs', 'Ancient Greek', 'Latin', 'Sanskrit'),
  (113, 'What is the fastest bird in a dive?', 'Peregrine falcon', 'Golden eagle', 'Osprey', 'Red-tailed hawk'),
  (114, 'What is the chemical symbol for silver?', 'Ag', 'Si', 'Sr', 'Al'),
  (115, 'Sound travels fastest through which?', 'Steel', 'Air', 'Water', 'A vacuum'),
  (116, 'How long does sunlight take to reach Earth?', 'About 8 minutes', 'About 8 seconds', 'About 8 hours', 'Instantly'),
  (117, 'Which blood cells fight infection?', 'White blood cells', 'Red blood cells', 'Platelets', 'Plasma'),
  (118, 'What is the largest species of shark?', 'Whale shark', 'Great white', 'Hammerhead', 'Tiger shark'),
  (119, 'Diamonds are made of which element?', 'Carbon', 'Silicon', 'Boron', 'Titanium'),
  (120, 'How many bones does a shark have?', 'Zero', '206', '88', '40'),
  (121, 'Tequila is made from which plant?', 'Agave', 'Cactus', 'Sugarcane', 'Corn'),
  (122, 'What is the main ingredient in borscht?', 'Beets', 'Cabbage', 'Potatoes', 'Tomatoes'),
  (123, 'Prosciutto is made from what meat?', 'Pork', 'Beef', 'Duck', 'Veal'),
  (124, 'What does IPA stand for in beer?', 'India Pale Ale', 'Irish Pale Ale', 'Imperial Pale Ale', 'International Pale Ale'),
  (125, 'A pluot is a hybrid of which two fruits?', 'Plum and apricot', 'Peach and plum', 'Pear and apricot', 'Plum and cherry'),
  (126, 'Worcestershire sauce contains which fish?', 'Anchovies', 'Sardines', 'Mackerel', 'Cod'),
  (127, 'Marzipan is made from which nut?', 'Almonds', 'Pistachios', 'Cashews', 'Walnuts'),
  (128, 'An espresso martini is vodka, espresso, and what?', 'Coffee liqueur', 'Irish cream', 'Amaretto', 'Dark rum'),
  (129, 'What score is a perfect game in bowling?', '300', '200', '250', '350'),
  (130, 'Which country invented golf?', 'Scotland', 'England', 'Ireland', 'United States'),
  (131, 'In tennis, what comes after deuce?', 'Advantage', 'Match point', 'Game', 'Sudden death'),
  (132, 'How many players does a hockey team have on the ice, goalie included?', 'Six', 'Five', 'Seven', 'Eight'),
  (133, 'What color jersey does the Tour de France leader wear?', 'Yellow', 'Green', 'White', 'Red'),
  (134, 'Which artist painted the Campbell''s soup cans?', 'Andy Warhol', 'Roy Lichtenstein', 'Jackson Pollock', 'Keith Haring'),
  (135, 'How many notes are in an octave, counting both ends?', 'Eight', 'Seven', 'Ten', 'Six'),
  (136, 'Which planet is Superman from?', 'Krypton', 'Vulcan', 'Xandar', 'Cybertron'),
  (137, 'Which instrument has 47 strings and 7 pedals?', 'The harp', 'The zither', 'The lute', 'The grand piano'),
  (138, 'In The Wizard of Oz, what did the Scarecrow want?', 'A brain', 'A heart', 'Courage', 'A way home'),
  (139, 'What is the Morse code pattern for SOS?', '3 dots, 3 dashes, 3 dots', '3 dashes, 3 dots, 3 dashes', '6 alternating dots and dashes', '9 dashes'),
  (140, 'Which chess pieces start next to the rooks?', 'The knights', 'The bishops', 'The pawns', 'The queens'),
  (141, 'A sommelier is an expert in what?', 'Wine', 'Cheese', 'Coffee', 'Chocolate'),
  (142, '"Tsunami" and "karaoke" come from which language?', 'Japanese', 'Chinese', 'Korean', 'Thai'),
  (144, 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Ga'),
  (146, 'Which is the smallest planet in our solar system?', 'Mercury', 'Mars', 'Venus', 'Earth'),
  (147, 'What force keeps the planets in orbit around the Sun?', 'Gravity', 'Magnetism', 'Friction', 'Electricity'),
  (148, 'Which vitamin is primarily produced by the skin when exposed to sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin K'),
  (149, 'What is the most abundant element in the universe?', 'Hydrogen', 'Helium', 'Oxygen', 'Carbon'),
  (150, 'Which part of the human eye controls the amount of light that enters it?', 'Iris', 'Cornea', 'Retina', 'Lens'),
  (152, 'At what temperature in Celsius does water boil at sea level?', '100', '90', '80', '120'),
  (153, 'Which scientist developed the theory of general relativity?', 'Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Niels Bohr'),
  (154, 'What is the chemical formula for common table salt?', 'NaCl', 'KCl', 'NaHCO3', 'CaCl2'),
  (155, 'What process do green plants use to convert sunlight into energy?', 'Photosynthesis', 'Respiration', 'Fermentation', 'Digestion'),
  (156, 'Which particle in an atom carries a negative electric charge?', 'Electron', 'Proton', 'Neutron', 'Positron'),
  (157, 'What is the largest organ of the human body?', 'Skin', 'Liver', 'Lungs', 'Brain'),
  (158, 'Which metal is the best conductor of electricity?', 'Silver', 'Copper', 'Gold', 'Aluminum'),
  (159, 'Which blood vessels carry blood away from the heart?', 'Arteries', 'Veins', 'Capillaries', 'Venules'),
  (160, 'How many chambers does the human heart have?', 'Four', 'Two', 'Three', 'Six'),
  (161, 'Which scientist formulated the three laws of motion?', 'Isaac Newton', 'Albert Einstein', 'Michael Faraday', 'James Clerk Maxwell'),
  (162, 'Which human organ filters waste from the blood to produce urine?', 'Kidneys', 'Liver', 'Bladder', 'Lungs'),
  (163, 'Which unit measures electrical resistance?', 'Ohm', 'Volt', 'Ampere', 'Watt'),
  (164, 'What is the dense central core of an atom called?', 'Nucleus', 'Electron shell', 'Orbital', 'Electron cloud'),
  (165, 'Which acid found in the human stomach helps to digest food?', 'Hydrochloric acid', 'Sulfuric acid', 'Citric acid', 'Acetic acid'),
  (166, 'Which is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Uranus'),
  (167, 'Which planet has the hottest surface in our solar system?', 'Venus', 'Mercury', 'Mars', 'Jupiter'),
  (168, 'Which planet orbits farthest from the Sun?', 'Neptune', 'Uranus', 'Saturn', 'Jupiter'),
  (169, 'Which planet rotates almost on its side, with an axis tilted close to ninety degrees?', 'Uranus', 'Neptune', 'Saturn', 'Venus'),
  (170, 'Which planet is best known for its bright and spectacular system of rings?', 'Saturn', 'Jupiter', 'Uranus', 'Neptune'),
  (171, 'The Sun is made up mostly of which two elements?', 'Hydrogen and helium', 'Oxygen and carbon', 'Hydrogen and oxygen', 'Helium and nitrogen'),
  (173, 'Which of these is a moon of the planet Saturn?', 'Titan', 'Europa', 'Triton', 'Phobos'),
  (174, 'Not counting the Sun, which is the brightest star seen in Earth''s night sky?', 'Sirius', 'Polaris', 'Betelgeuse', 'Vega'),
  (175, 'What is the nearest major galaxy to our own Milky Way?', 'Andromeda', 'Triangulum', 'Whirlpool', 'Sombrero'),
  (176, 'Halley''s Comet becomes visible from Earth roughly once every how many years?', '76', '12', '33', '240'),
  (177, 'What is the name for the event in which the Moon passes directly between the Sun and the Earth?', 'Solar eclipse', 'Lunar eclipse', 'Equinox', 'Meteor shower'),
  (178, 'What do we call a piece of space rock that survives its fall through the atmosphere and lands on the ground?', 'Meteorite', 'Meteor', 'Asteroid', 'Comet'),
  (179, 'Which of these is an igneous rock?', 'Granite', 'Limestone', 'Marble', 'Sandstone'),
  (180, 'What is the outermost solid layer of the Earth called?', 'Crust', 'Mantle', 'Outer core', 'Inner core'),
  (181, 'Which metal makes up most of the Earth''s core?', 'Iron', 'Nickel', 'Gold', 'Copper'),
  (183, 'Approximately what percentage of the Earth''s surface is covered by water?', '71 percent', '51 percent', '61 percent', '81 percent'),
  (184, 'What is the largest hot desert in the world?', 'Sahara', 'Gobi', 'Kalahari', 'Arabian'),
  (185, 'What is the name for the regular daily rise and fall of the ocean''s water level?', 'Tides', 'Currents', 'Waves', 'Swells'),
  (186, 'The ozone layer is found mainly in which layer of the atmosphere?', 'Stratosphere', 'Troposphere', 'Mesosphere', 'Thermosphere'),
  (187, 'The Saffir Simpson scale is used to measure the strength of which type of storm?', 'Hurricanes', 'Tornadoes', 'Blizzards', 'Thunderstorms'),
  (188, 'Which country has the city of Marrakesh?', 'Morocco', 'Egypt', 'Tunisia', 'Algeria'),
  (189, 'The Danube River flows into which sea?', 'Black Sea', 'Caspian Sea', 'Baltic Sea', 'Adriatic Sea'),
  (190, 'Which country is home to the ancient city of Petra?', 'Jordan', 'Egypt', 'Lebanon', 'Syria'),
  (191, 'Which desert covers much of southern Africa across Botswana and Namibia?', 'Kalahari', 'Sahara', 'Namib', 'Atacama'),
  (192, 'The Suez Canal connects the Mediterranean Sea to which body of water?', 'Red Sea', 'Black Sea', 'Caspian Sea', 'Arabian Sea'),
  (193, 'Which country is home to the Galapagos Islands?', 'Ecuador', 'Peru', 'Colombia', 'Chile'),
  (194, 'The Great Barrier Reef lies off the coast of which country?', 'Australia', 'Indonesia', 'Philippines', 'New Zealand'),
  (195, 'What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'),
  (196, 'Which mountain range separates Europe from Asia?', 'Ural Mountains', 'Caucasus Mountains', 'Carpathian Mountains', 'Alps'),
  (197, 'The Angel Falls, the world''s tallest waterfall, is found in which country?', 'Venezuela', 'Brazil', 'Colombia', 'Guyana'),
  (198, 'Which country is home to the city of Timbuktu?', 'Mali', 'Niger', 'Chad', 'Sudan'),
  (199, 'What is the capital of New Zealand?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton'),
  (200, 'Lake Titicaca sits on the border of Bolivia and which country?', 'Peru', 'Chile', 'Ecuador', 'Paraguay'),
  (201, 'Which sea lies between Italy and the Balkan Peninsula?', 'Adriatic Sea', 'Aegean Sea', 'Tyrrhenian Sea', 'Ionian Sea'),
  (202, 'Mount Fuji is located in which country?', 'Japan', 'South Korea', 'China', 'Taiwan'),
  (203, 'Which country contains most of the Amazon rainforest?', 'Brazil', 'Peru', 'Colombia', 'Bolivia'),
  (204, 'The Victoria Falls lie on the border of Zimbabwe and which country?', 'Zambia', 'Botswana', 'Mozambique', 'Namibia'),
  (205, 'Which river runs through the city of Cairo?', 'Nile', 'Euphrates', 'Tigris', 'Jordan'),
  (206, 'The Matterhorn straddles the border between Switzerland and which country?', 'Italy', 'France', 'Austria', 'Germany'),
  (207, 'Which country is home to the temple complex of Angkor Wat?', 'Cambodia', 'Thailand', 'Vietnam', 'Laos'),
  (208, 'What is the capital of Brazil?', 'Brasilia', 'Rio de Janeiro', 'Sao Paulo', 'Salvador'),
  (209, 'The Rock of Gibraltar sits at the entrance to which sea?', 'Mediterranean Sea', 'Red Sea', 'Black Sea', 'Baltic Sea'),
  (210, 'Which ancient civilization built the pyramids at Giza?', 'The Egyptians', 'The Sumerians', 'The Persians', 'The Phoenicians'),
  (211, 'Who was the first Emperor of Rome?', 'Augustus', 'Julius Caesar', 'Nero', 'Constantine'),
  (212, 'Which explorer led the first expedition to circumnavigate the globe?', 'Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama', 'Amerigo Vespucci'),
  (213, 'Which war was fought between the North and South regions of the United States?', 'The American Civil War', 'The War of 1812', 'The Revolutionary War', 'The Mexican War'),
  (214, 'Who wrote the Communist Manifesto with Friedrich Engels?', 'Karl Marx', 'Vladimir Lenin', 'Leon Trotsky', 'Joseph Stalin'),
  (215, 'The Renaissance began in which country?', 'Italy', 'France', 'England', 'Spain'),
  (216, 'Which queen ruled England during a golden age that included Shakespeare?', 'Elizabeth I', 'Victoria', 'Mary I', 'Anne'),
  (217, 'Who was the leader of the Soviet Union during most of World War Two?', 'Joseph Stalin', 'Vladimir Lenin', 'Nikita Khrushchev', 'Leon Trotsky'),
  (218, 'Which document, signed in 1215, limited the power of the English king?', 'The Magna Carta', 'The Bill of Rights', 'The Domesday Book', 'The Treaty of Versailles'),
  (219, 'Who was the French military leader who crowned himself Emperor in 1804?', 'Napoleon Bonaparte', 'Louis XVI', 'Charles de Gaulle', 'Robespierre'),
  (220, 'Which empire was ruled by Genghis Khan?', 'The Mongol Empire', 'The Ottoman Empire', 'The Persian Empire', 'The Byzantine Empire'),
  (221, 'The Industrial Revolution first began in which country?', 'Britain', 'Germany', 'The United States', 'France'),
  (222, 'Who led India in its nonviolent independence movement against British rule?', 'Mahatma Gandhi', 'Jawaharlal Nehru', 'Nelson Mandela', 'Ho Chi Minh'),
  (223, 'Which civilization is credited with building Machu Picchu in South America?', 'The Inca', 'The Aztec', 'The Maya', 'The Olmec'),
  (224, 'Who was the ancient Greek conqueror who created an empire stretching to India?', 'Alexander the Great', 'Julius Caesar', 'Hannibal', 'Leonidas'),
  (225, 'Which explorer is credited with reaching the Americas in 1492?', 'Christopher Columbus', 'Marco Polo', 'Leif Erikson', 'John Cabot'),
  (226, 'The Ottoman Empire was centered in the country known today as what?', 'Turkey', 'Iran', 'Egypt', 'Greece'),
  (227, 'Who was the American president during the Civil War?', 'Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'Andrew Jackson'),
  (229, 'The Cold War was primarily a rivalry between the United States and which nation?', 'The Soviet Union', 'China', 'Germany', 'Japan'),
  (230, 'Which South African leader was imprisoned for 27 years before becoming president?', 'Nelson Mandela', 'Desmond Tutu', 'Kwame Nkrumah', 'Jomo Kenyatta'),
  (231, 'The assassination of which archduke helped trigger World War One?', 'Franz Ferdinand', 'Otto von Bismarck', 'Kaiser Wilhelm II', 'Nicholas II'),
  (232, 'Who wrote the novel Pride and Prejudice?', 'Jane Austen', 'Charlotte Bronte', 'Emily Bronte', 'George Eliot'),
  (233, 'Who composed the Ninth Symphony that includes the Ode to Joy?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'),
  (234, 'Which painter is famous for cutting off part of his own ear?', 'Vincent van Gogh', 'Paul Gauguin', 'Claude Monet', 'Paul Cezanne'),
  (235, 'Who wrote the novel War and Peace?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Turgenev'),
  (236, 'Who composed the set of violin concertos known as The Four Seasons?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'George Frideric Handel', 'Arcangelo Corelli'),
  (237, 'Who painted Girl with a Pearl Earring?', 'Johannes Vermeer', 'Rembrandt', 'Frans Hals', 'Jan Steen'),
  (238, 'Who composed the opera The Marriage of Figaro?', 'Wolfgang Amadeus Mozart', 'Giuseppe Verdi', 'Giacomo Puccini', 'Gioachino Rossini'),
  (239, 'Who wrote the novel One Hundred Years of Solitude?', 'Gabriel Garcia Marquez', 'Mario Vargas Llosa', 'Jorge Luis Borges', 'Isabel Allende'),
  (240, 'Who wrote the novel The Old Man and the Sea?', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck', 'Mark Twain'),
  (241, 'Who composed the ballets Swan Lake and The Nutcracker?', 'Pyotr Ilyich Tchaikovsky', 'Igor Stravinsky', 'Sergei Rachmaninoff', 'Modest Mussorgsky'),
  (242, 'Who wrote the tragedy Macbeth?', 'William Shakespeare', 'Christopher Marlowe', 'Ben Jonson', 'John Webster'),
  (243, 'Who painted the famous series of Water Lilies?', 'Claude Monet', 'Edgar Degas', 'Camille Pissarro', 'Edouard Manet'),
  (244, 'Who wrote the novel Crime and Punishment?', 'Fyodor Dostoevsky', 'Leo Tolstoy', 'Nikolai Gogol', 'Anton Chekhov'),
  (245, 'Who painted The Scream?', 'Edvard Munch', 'Gustav Klimt', 'Egon Schiele', 'Wassily Kandinsky'),
  (246, 'Which band released the album Abbey Road?', 'The Beatles', 'The Rolling Stones', 'The Who', 'The Kinks'),
  (247, 'Who wrote the novel Don Quixote?', 'Miguel de Cervantes', 'Lope de Vega', 'Federico Garcia Lorca', 'Benito Perez Galdos'),
  (248, 'Which American poet wrote The Raven?', 'Edgar Allan Poe', 'Walt Whitman', 'Emily Dickinson', 'Robert Frost'),
  (249, 'Which musician was known as the King of Rock and Roll?', 'Elvis Presley', 'Chuck Berry', 'Little Richard', 'Buddy Holly'),
  (250, 'Which Renaissance artist painted The Birth of Venus?', 'Sandro Botticelli', 'Raphael', 'Titian', 'Giorgione'),
  (251, 'Who directed the 1975 thriller Jaws?', 'Steven Spielberg', 'Martin Scorsese', 'George Lucas', 'Ridley Scott'),
  (252, 'In the 1939 film The Wizard of Oz, what color are Dorothy''s magical slippers?', 'Red', 'Silver', 'Blue', 'Green'),
  (253, 'Which actor plays the whip carrying archaeologist in the Indiana Jones film series?', 'Harrison Ford', 'Mel Gibson', 'Kurt Russell', 'Michael Douglas'),
  (254, 'What is the name of the coffee house where the friends gather in the sitcom Friends?', 'Central Perk', 'The Grind', 'Central Bean', 'Java Joe''s'),
  (255, 'Which 1991 film features Hannibal Lecter and FBI trainee Clarice Starling?', 'The Silence of the Lambs', 'Se7en', 'Zodiac', 'The Bone Collector'),
  (256, 'In the original Star Wars trilogy, who is revealed to be Luke Skywalker''s father?', 'Darth Vader', 'Han Solo', 'Yoda', 'Emperor Palpatine'),
  (257, 'Which actor played Jack Dawson in the 1997 film Titanic?', 'Leonardo DiCaprio', 'Brad Pitt', 'Johnny Depp', 'Matt Damon'),
  (258, 'Who directed the 1994 crime film Pulp Fiction?', 'Quentin Tarantino', 'Guy Ritchie', 'Robert Rodriguez', 'Oliver Stone'),
  (259, 'In the television series Breaking Bad, what subject did Walter White teach at high school?', 'Chemistry', 'Biology', 'Physics', 'Mathematics'),
  (260, 'In the Pixar film Finding Nemo, what type of fish is Nemo?', 'Clownfish', 'Angelfish', 'Goldfish', 'Blue tang'),
  (261, 'Which hobbit is played by Elijah Wood in The Lord of the Rings films?', 'Frodo Baggins', 'Bilbo Baggins', 'Samwise Gamgee', 'Peregrin Took'),
  (262, 'The famous line Here''s looking at you, kid comes from which classic film?', 'Casablanca', 'Gone with the Wind', 'Citizen Kane', 'The Maltese Falcon'),
  (263, 'Which actor played the Joker in the 2008 film The Dark Knight?', 'Heath Ledger', 'Jack Nicholson', 'Jared Leto', 'Joaquin Phoenix'),
  (264, 'Who is the youngest child of Homer and Marge Simpson?', 'Maggie', 'Lisa', 'Bart', 'Ralph'),
  (265, 'Who directed the 1972 crime film The Godfather?', 'Francis Ford Coppola', 'Martin Scorsese', 'Brian De Palma', 'Sidney Lumet'),
  (266, 'Which actress played Hermione Granger in the Harry Potter films?', 'Emma Watson', 'Emma Stone', 'Emma Thompson', 'Keira Knightley'),
  (267, 'In Back to the Future, which character is the eccentric scientist who builds the time machine?', 'Doc Brown', 'Marty McFly', 'Biff Tannen', 'George McFly'),
  (268, 'The line Life is like a box of chocolates comes from which film?', 'Forrest Gump', 'Rain Man', 'Big Fish', 'The Green Mile'),
  (269, 'Who directed the science fiction films Alien and Blade Runner?', 'Ridley Scott', 'James Cameron', 'George Lucas', 'Stanley Kubrick'),
  (270, 'In the American version of The Office, Steve Carell plays which regional manager?', 'Michael Scott', 'Jim Halpert', 'Dwight Schrute', 'Andy Bernard'),
  (271, 'Which 2009 film directed by James Cameron is set on the lush moon Pandora?', 'Avatar', 'Prometheus', 'Interstellar', 'District 9'),
  (272, 'Who provides the voice of the cowboy Woody in the Toy Story films?', 'Tom Hanks', 'Tim Allen', 'Billy Crystal', 'Robin Williams'),
  (273, 'Traditional Italian pesto alla genovese uses which herb as its main ingredient?', 'Basil', 'Parsley', 'Oregano', 'Coriander'),
  (275, 'Which gas is produced by yeast and causes bread dough to rise?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'),
  (278, 'Balsamic vinegar traditionally comes from which country?', 'Italy', 'France', 'Spain', 'Greece'),
  (279, 'Which vegetable is the main ingredient in the dip baba ganoush?', 'Eggplant', 'Chickpea', 'Zucchini', 'Cucumber'),
  (281, 'Sauerkraut, a fermented food popular in Germany, is made from which vegetable?', 'Cabbage', 'Carrot', 'Onion', 'Turnip'),
  (282, 'The English word salary is derived from the Latin word for which substance, once used as payment?', 'Salt', 'Gold', 'Bread', 'Silver'),
  (283, 'The fermented side dish kimchi is a staple of which country''s cuisine?', 'Korea', 'Japan', 'China', 'Vietnam'),
  (284, 'Champagne can only officially be called Champagne if it is produced in which country?', 'France', 'Italy', 'Spain', 'Germany'),
  (285, 'Which type of pastry is used to make traditional profiteroles and eclairs?', 'Choux', 'Puff', 'Shortcrust', 'Filo'),
  (286, 'The Maillard reaction is responsible for what characteristic in cooked food?', 'Browning', 'Souring', 'Thickening', 'Freezing'),
  (287, 'Which grain is used to make traditional risotto?', 'Rice', 'Wheat', 'Barley', 'Oats'),
  (288, 'The Scoville scale used for chilli peppers measures the concentration of which compound?', 'Capsaicin', 'Caffeine', 'Menthol', 'Fructose'),
  (289, 'The word sandwich is commonly said to come from a person who held which title?', 'Earl', 'Duke', 'Baron', 'Viscount'),
  (290, 'Which country is the world''s largest producer of tea?', 'China', 'India', 'Kenya', 'Sri Lanka'),
  (291, 'Which mineral dissolved in water is a primary cause of what is commonly called hard water?', 'Calcium', 'Sodium', 'Iron', 'Potassium'),
  (292, 'The French kitchen phrase mise en place broadly refers to which activity done before cooking?', 'Preparation', 'Plating', 'Seasoning', 'Cleaning'),
  (293, 'Traditional single malt Scotch whisky is made from which grain?', 'Barley', 'Corn', 'Rye', 'Wheat'),
  (294, 'The Italian cooking term al dente literally translates to which phrase?', 'To the tooth', 'To the taste', 'To the fork', 'To the pan'),
  (295, 'How many players are on the field for one soccer team at kickoff?', 'Eleven', 'Nine', 'Ten', 'Twelve'),
  (297, 'Which country traditionally hosts the Wimbledon tennis championships?', 'England', 'France', 'Australia', 'United States'),
  (298, 'How many rings appear on the Olympic flag?', 'Five', 'Four', 'Six', 'Seven'),
  (299, 'In a standard deck of playing cards, how many cards are there without jokers?', 'Fifty two', 'Forty eight', 'Fifty four', 'Sixty'),
  (300, 'What is the maximum score possible from a single dart thrown at a dartboard?', 'Sixty', 'Fifty', 'Fifty seven', 'Forty five'),
  (301, 'Which stroke is generally regarded as the fastest in competitive swimming?', 'Freestyle', 'Breaststroke', 'Backstroke', 'Butterfly'),
  (302, 'In golf, what term describes a score of one under par on a hole?', 'Birdie', 'Eagle', 'Bogey', 'Albatross'),
  (303, 'Which athlete was famously known as The Greatest and lit the 1996 Olympic cauldron?', 'Muhammad Ali', 'Joe Frazier', 'Mike Tyson', 'Sugar Ray Robinson'),
  (304, 'In tennis, what is the term for a score of forty forty?', 'Deuce', 'Advantage', 'Let', 'Fault'),
  (306, 'Which sport uses terms such as scrum, lineout, and fly half?', 'Rugby', 'Cricket', 'Lacrosse', 'Field hockey'),
  (307, 'In the board game Monopoly, which color group contains Boardwalk in the classic US edition?', 'Dark blue', 'Green', 'Yellow', 'Brown'),
  (308, 'In which sport do teams compete for the Ryder Cup?', 'Golf', 'Tennis', 'Rowing', 'Sailing'),
  (309, 'Which martial art originated in Japan and means the gentle way?', 'Judo', 'Taekwondo', 'Kung fu', 'Muay Thai'),
  (310, 'In basketball, how many points is a standard free throw worth?', 'One', 'Two', 'Three', 'Four'),
  (311, 'The Tour de France is a major international competition in which sport?', 'Cycling', 'Marathon running', 'Motor racing', 'Rowing'),
  (312, 'In chess, which is the only piece that can jump over other pieces?', 'Knight', 'Queen', 'Bishop', 'Rook'),
  (313, 'How many strikes in a row make up a turkey in bowling?', 'Three', 'Two', 'Four', 'Five'),
  (314, 'Which country is credited with inventing the modern game of table tennis?', 'England', 'China', 'Japan', 'Sweden'),
  (315, 'In the game of poker, which hand ranks highest?', 'Royal flush', 'Four of a kind', 'Full house', 'Straight flush');

-- --- Wordy (121 words) ---
insert into wordy_words (word) values
  ('ACTOR'),
  ('APPLE'),
  ('BACON'),
  ('BEACH'),
  ('BERRY'),
  ('BOARD'),
  ('BRAVE'),
  ('BREAD'),
  ('CABIN'),
  ('CANDY'),
  ('CHAIR'),
  ('CHALK'),
  ('CIDER'),
  ('CLOCK'),
  ('CLOUD'),
  ('COACH'),
  ('COURT'),
  ('CREAM'),
  ('CRISP'),
  ('CROWN'),
  ('DAISY'),
  ('DANCE'),
  ('DIZZY'),
  ('DREAM'),
  ('EAGLE'),
  ('EARTH'),
  ('FANCY'),
  ('FEAST'),
  ('FERRY'),
  ('FIELD'),
  ('FLAME'),
  ('FLOUR'),
  ('FROST'),
  ('GIANT'),
  ('GLASS'),
  ('GRAND'),
  ('GRAPE'),
  ('HAPPY'),
  ('HEART'),
  ('HONEY'),
  ('HOUSE'),
  ('IVORY'),
  ('JOLLY'),
  ('JUICE'),
  ('JUMBO'),
  ('KNIFE'),
  ('KOALA'),
  ('LEMON'),
  ('LIGHT'),
  ('LODGE'),
  ('LOYAL'),
  ('LUCKY'),
  ('MANGO'),
  ('MAPLE'),
  ('MEDAL'),
  ('MELON'),
  ('MERRY'),
  ('MOVIE'),
  ('MUSIC'),
  ('NIGHT'),
  ('NOBLE'),
  ('NORTH'),
  ('OCEAN'),
  ('OLIVE'),
  ('ONION'),
  ('PAPER'),
  ('PARTY'),
  ('PEACH'),
  ('PEARL'),
  ('PHONE'),
  ('PIANO'),
  ('PLANT'),
  ('PLATE'),
  ('PLUMP'),
  ('POINT'),
  ('PRIZE'),
  ('PROUD'),
  ('QUEEN'),
  ('QUILT'),
  ('RADIO'),
  ('RIVER'),
  ('ROBIN'),
  ('SALAD'),
  ('SCORE'),
  ('SHELL'),
  ('SHINY'),
  ('SHORE'),
  ('SMART'),
  ('SMILE'),
  ('SOUND'),
  ('SPACE'),
  ('SPICE'),
  ('SPOON'),
  ('SPORT'),
  ('STAGE'),
  ('STEAK'),
  ('STONE'),
  ('STORM'),
  ('SUGAR'),
  ('SUNNY'),
  ('SWIFT'),
  ('TABLE'),
  ('TASTY'),
  ('TIGER'),
  ('TOAST'),
  ('TOWER'),
  ('TRAIN'),
  ('UNITY'),
  ('URBAN'),
  ('VIVID'),
  ('VOICE'),
  ('VOWEL'),
  ('WAGON'),
  ('WATER'),
  ('WHALE'),
  ('WHEAT'),
  ('WINDY'),
  ('WORLD'),
  ('YACHT'),
  ('ZEBRA'),
  ('ZESTY');

-- --- Who Invited You? (44 words) ---
insert into wiy_words (id, category, word) overriding system value values
  (1, 'Food and drink', 'Pizza'),
  (2, 'Food and drink', 'Tacos'),
  (3, 'Food and drink', 'Sushi'),
  (4, 'Food and drink', 'Pancakes'),
  (5, 'Food and drink', 'Bacon'),
  (6, 'Food and drink', 'Coffee'),
  (7, 'Food and drink', 'Ice cream'),
  (8, 'Food and drink', 'Buffalo wings'),
  (9, 'Food and drink', 'Nachos'),
  (18, 'Night out', 'Karaoke'),
  (19, 'Night out', 'Bartender'),
  (20, 'Night out', 'Happy hour'),
  (21, 'Night out', 'Jukebox'),
  (22, 'Night out', 'Bouncer'),
  (23, 'Night out', 'Last call'),
  (24, 'Night out', 'Pool table'),
  (25, 'Night out', 'Darts'),
  (26, 'Around the house', 'Couch'),
  (27, 'Around the house', 'Lawn mower'),
  (28, 'Around the house', 'Garage'),
  (29, 'Around the house', 'Dishwasher'),
  (30, 'Around the house', 'Junk drawer'),
  (31, 'Around the house', 'Thermostat'),
  (32, 'Jobs', 'Dentist'),
  (33, 'Jobs', 'Plumber'),
  (34, 'Jobs', 'Teacher'),
  (35, 'Jobs', 'Barber'),
  (36, 'Jobs', 'Mail carrier'),
  (37, 'Jobs', 'DJ'),
  (38, 'Movies and TV', 'Jaws'),
  (39, 'Movies and TV', 'Rocky'),
  (40, 'Movies and TV', 'Batman'),
  (41, 'Movies and TV', 'The Office'),
  (42, 'Movies and TV', 'Jeopardy'),
  (43, 'Sports', 'Home run'),
  (44, 'Sports', 'Tailgate'),
  (45, 'Sports', 'Referee'),
  (46, 'Sports', 'Golf cart'),
  (47, 'Sports', 'Slam dunk'),
  (48, 'Travel', 'Airport'),
  (49, 'Travel', 'Road trip'),
  (50, 'Travel', 'Cruise ship'),
  (51, 'Travel', 'Motel'),
  (52, 'Travel', 'Passport');

-- --- Fortune Teller (106 fortunes) ---
insert into fortunes (id, text) overriding system value values
  (1, 'Good news is already on its way. It got a little lost, that is all.'),
  (2, 'You will soon make the decision you have been putting off. It goes fine.'),
  (3, 'An unexpected compliment lands this week. Accept it without arguing.'),
  (4, 'Something you lost is closer than you think.'),
  (6, 'A small risk pays off soon. Not the big one. The small one.'),
  (7, 'Someone is about to take your advice. Try to look surprised.'),
  (8, 'Your patience is about to be rewarded. Keep pretending you have it.'),
  (9, 'An old friend resurfaces with a story worth hearing.'),
  (10, 'You will soon be in the right place at the right time. Stay put.'),
  (11, 'Say yes to the next invitation. Especially the weird one.'),
  (12, 'The compliment you almost gave someone, give it. It lands.'),
  (13, 'Money finds you this month. Not a fortune. Enough for dessert.'),
  (14, 'Your luck changes direction soon. It was already pointed the right way.'),
  (15, 'The answer you are waiting for arrives just before you stop caring.'),
  (16, 'Someone thinks of you more often than you would guess.'),
  (17, 'A skill you forgot you had is about to come in handy.'),
  (18, 'Trust the plan you made before you started second-guessing it.'),
  (19, 'The best part of your week has not happened yet.'),
  (20, 'You are one good night of sleep away from a great idea.'),
  (21, 'A door you thought was closed is just heavy. Push again.'),
  (22, 'Your next big laugh sneaks up on you. Do not spoil it by waiting.'),
  (25, 'Someone owes you a favor and remembers it. Let them pay it back.'),
  (26, 'Your instincts are sharper than your doubts this month. Act accordingly.'),
  (27, 'A plan made tonight actually happens. Rare, but true.'),
  (28, 'Big changes start small. Yours already started.'),
  (30, 'Someone new will laugh at your oldest joke. Keep telling it.'),
  (31, 'The errand you dread takes five minutes. It always did.'),
  (32, 'Your comfort zone misses you. Do not go back yet.'),
  (33, 'What you practice in private gets noticed in public soon.'),
  (34, 'The next thing you make with your hands turns out better than expected.'),
  (36, 'An answer arrives disguised as a coincidence.'),
  (40, 'You will win an argument by staying out of it.'),
  (41, 'The habit you started quietly is working. Keep it quiet a little longer.'),
  (43, 'Someone is proud of you and bad at saying it. Assume it daily.'),
  (44, 'A yes you are scared to say becomes a story you love to tell.'),
  (45, 'The luck you make beats the luck you wait for. Make some tonight.'),
  (46, 'A pleasant surprise is waiting for you.'),
  (47, 'Your hard work is about to pay off.'),
  (48, 'You will soon cross paths with someone worth knowing.'),
  (49, 'Good things are coming. Some of them are already here.'),
  (50, 'A fresh start is closer than it looks.'),
  (51, 'Someone admires you from a polite distance.'),
  (52, 'The kindness you gave away is on its way back.'),
  (53, 'Fortune favors you more than you have noticed.'),
  (54, 'An opportunity you almost missed circles back for another pass.'),
  (55, 'Your smile will be the best part of someone''s day.'),
  (56, 'You are about to hear exactly what you needed to hear.'),
  (57, 'A small act of generosity returns to you, with interest.'),
  (58, 'The best is yet to come, and it is not far.'),
  (59, 'Someone will soon ask for your opinion. They mean it.'),
  (60, 'Your next good laugh is closer than your next worry.'),
  (61, 'You will soon find something you were not looking for. Keep it.'),
  (62, 'Patience now, applause later.'),
  (63, 'What you are hoping for is hoping for you too.'),
  (64, 'Trust yourself. Everyone else already does.'),
  (65, 'Your generosity will be remembered longer than you expect.'),
  (66, 'Something you planted a while ago is about to bloom.'),
  (67, 'A stranger''s kindness will reach you before the week is out.'),
  (68, 'The path you are on is better than it looks from where you stand.'),
  (69, 'Good company finds you easily. Tonight is proof.'),
  (70, 'What you are hoping for is hoping for you too.'),
  (71, 'A quiet effort will bring a loud reward.'),
  (72, 'A door opens this month that you did not knock on.'),
  (73, 'The next chapter is better written than the last.'),
  (74, 'Someone will remember tonight because of you.'),
  (75, 'You are closer to the finish line than the starting line.'),
  (76, 'A good idea chooses you this week. Give it a chance.'),
  (77, 'The right words will find you at the right moment.'),
  (78, 'What feels like waiting is really preparing.'),
  (79, 'A warm welcome is waiting somewhere you have not been yet.'),
  (80, 'Your generosity will outlive the moment it cost you.'),
  (81, 'Your curiosity will lead you somewhere wonderful.'),
  (82, 'An ordinary day this week turns out to be a favorite.'),
  (83, 'You will soon have a reason to celebrate. Start planning.'),
  (84, 'A friendship begun by accident will last on purpose.'),
  (85, 'Luck is loyal to those who keep showing up. Keep showing up.'),
  (86, 'You will find beauty in a place you usually hurry past.'),
  (87, 'Someone is telling a good story about you right now.'),
  (88, 'The advice you give this week will be better than you know.'),
  (89, 'A wish you almost gave up on is still in motion.'),
  (90, 'Your calendar hides a very good day in the near future.'),
  (91, 'The work you love will soon love you back.'),
  (92, 'A leap you take soon lands softly.'),
  (93, 'You will be exactly where you are needed this week.'),
  (94, 'Something borrowed comes back with a thank-you attached.'),
  (95, 'Your name comes up soon, in the best possible way.'),
  (96, 'The horizon holds more for you than the rearview.'),
  (97, 'An open mind tonight brings an open door tomorrow.'),
  (98, 'A song you love finds you twice this week. Take it as a sign.'),
  (99, 'You will teach someone something without even trying.'),
  (100, 'Comfort arrives from an unexpected direction.'),
  (101, 'Your best season is still ahead of you.'),
  (102, 'Tonight''s laughter will outlast tonight.'),
  (103, 'Someone is grateful for you and about to say so.'),
  (104, 'What you share tonight multiplies.'),
  (105, 'The first step you already took counts more than you think.'),
  (106, 'Your kindness has better aim than you realize.'),
  (107, 'A familiar place will show you something new.'),
  (108, 'Time spent in good company is never wasted.'),
  (109, 'The news you are dreading turns out smaller than it looked.'),
  (110, 'You will soon outgrow a worry that once fit you.'),
  (111, 'A promise kept this week becomes a story told for years.'),
  (112, 'Your gratitude is about to be answered.'),
  (113, 'The stars have been busy arranging something nice for you.'),
  (114, 'You will soon trade a worry for a wonder.'),
  (115, 'Tomorrow is friendlier than it looks from here.');

-- --- All Talk (58 categories) ---
insert into at_categories (id, category) overriding system value values
  (1, 'dog breeds'),
  (2, 'pizza toppings'),
  (3, 'ice cream flavors'),
  (4, 'US states'),
  (5, 'state capitals'),
  (6, 'countries in Europe'),
  (7, 'countries in Africa'),
  (8, 'NFL teams'),
  (9, 'MLB teams'),
  (10, 'NBA teams'),
  (11, 'Olympic sports'),
  (12, 'breakfast cereals'),
  (13, 'fast food chains'),
  (14, 'soda brands'),
  (15, 'beer brands'),
  (16, 'cocktails'),
  (17, 'types of cheese'),
  (18, 'types of pasta'),
  (19, 'fruits'),
  (20, 'vegetables'),
  (21, 'herbs and spices'),
  (22, 'candy bars'),
  (23, 'board games'),
  (24, 'card games'),
  (25, 'Disney animated movies'),
  (26, 'superheroes'),
  (27, 'TV sitcoms'),
  (28, 'Beatles songs'),
  (29, 'Christmas songs'),
  (30, 'nursery rhymes'),
  (31, 'zoo animals'),
  (32, 'ocean animals'),
  (33, 'birds'),
  (34, 'insects'),
  (35, 'flowers'),
  (36, 'car brands'),
  (37, 'airlines'),
  (38, 'kitchen utensils'),
  (39, 'tools in a toolbox'),
  (40, 'things in a wallet'),
  (41, 'things at the beach'),
  (42, 'school subjects'),
  (43, 'languages'),
  (44, 'world capitals'),
  (45, 'rivers'),
  (46, 'US presidents'),
  (47, 'Greek gods'),
  (48, 'elements on the periodic table'),
  (49, 'condiments'),
  (50, 'types of sandwiches'),
  (51, 'donut flavors'),
  (52, 'cartoon characters'),
  (53, 'Star Wars characters'),
  (54, 'horror movies'),
  (55, 'ways to cook an egg'),
  (56, 'things that are yellow'),
  (57, 'jobs with uniforms'),
  (58, 'slang words for money');

-- --- advance the identity sequences past the explicit ids ---
select setval(pg_get_serial_sequence('gts_questions','id'),    (select max(id) from gts_questions));
select setval(pg_get_serial_sequence('wkw_questions','id'),    (select max(id) from wkw_questions));
select setval(pg_get_serial_sequence('trivia_questions','id'), (select max(id) from trivia_questions));
select setval(pg_get_serial_sequence('wiy_words','id'),        (select max(id) from wiy_words));
select setval(pg_get_serial_sequence('fortunes','id'),         (select max(id) from fortunes));
select setval(pg_get_serial_sequence('at_categories','id'),    (select max(id) from at_categories));

-- ============================================================================
--  Done. Row check:
--    select 'gts' g, count(*) from gts_questions
--    union all select 'wkw', count(*) from wkw_questions
--    union all select 'trivia', count(*) from trivia_questions
--    union all select 'wordy', count(*) from wordy_words
--    union all select 'wiy', count(*) from wiy_words
--    union all select 'fortunes', count(*) from fortunes
--    union all select 'all_talk', count(*) from at_categories;
--  Expect: 43 / 136 / 293 / 121 / 44 / 106 / 58.
-- ============================================================================